name: CI-CD Pipeline v2
 
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
 
jobs:
 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only needs to read code
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
 
      - name: Lint JavaScript
        run: npx eslint javascript.js || true
 
      - name: Sonar Scan
        uses: SonarSource/sonarqube-scan-action@8dbbf266ab49d71bd54c1ed1a7eb1e13e434f5dc
        with:
          args: >
            -Dsonar.projectKey=kprusty-338_DevOps
            -Dsonar.organization=kprusty-338
        env:
          SONAR_TOKEN: ${{ secrets.secret_token }}
          SONAR_HOST_URL: https://sonarcloud.io
 
      - name: Build
        run: |
          mkdir temp
          cp index.html temp/
          cp style.css temp/
          cp app.js temp/
 
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: temp/
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write       # Needed to deploy
      id-token: write    # Required for secure OIDC auth
 
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
