name: CI-CD Pipeline v2
 
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
 
jobs:
 
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read   # Only needs to read code
 
    steps:
      - name: Checkout
        uses: actions/checkout@v4
 
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
 
      - name: Lint JavaScript
        run: npx eslint javascript.js || true
 
      - name: Sonar Scan
        # use released tag; SHA previously unavailable leading to download errors
        uses: SonarSource/sonarqube-scan-action@v5.0.0
        with:
          args: >
            -Dsonar.projectKey=jonnamohit_CI-CD
            -Dsonar.organization=jonnamohit
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
    
 
      - name: Build
        run: |
          mkdir temp
          cp index.html temp/
          cp styles.css temp/
          cp script.js temp/
 
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: temp/
 
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write       # Needed to deploy
      id-token: write    # Required for secure OIDC auth
 
    steps:
      - name: Deploy
        uses: actions/deploy-pages@v4
